name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend, Lambda, and Frontend to AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: 461frontend

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy backend to EC2
      - name: Deploy Backend to EC2
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem
          scp -o StrictHostKeyChecking=no -i ec2-key.pem -r ./backend/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/backend2/
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            cd /home/ec2-user/backend2
            pm2 restart index.js || pm2 start index.js
          EOF

      # Zip and deploy Lambda functions
      - name: Deploy Lambda Functions
        run: |
          cd lambda
          for folder in */; do
            zip -r "${folder%/}.zip" "$folder"
            aws lambda update-function-code --function-name "${folder%/}" --zip-file fileb://${folder%/}.zip
          done

      # Deploy Frontend to S3
      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./my-frontend-new s3://$S3_BUCKET/ --delete
